---
- name: Setup Spark
  hosts: jn
  become: true
  vars:
    hadoop_user: hadoop
    hadoop_home: /home/hadoop
    hadoop_version: 3.4.0
    hive_version: 4.0.0
    spark_version: 3.5.6
    spark_download_url: "https://archive.apache.org/dist/spark/spark-3.5.6/spark-3.5.6-bin-hadoop3.tgz"
    venv_path: "{{ hadoop_home }}/venv"
  roles:
    - role: spark
